name: ML CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          pip install -r MLProject/requirements.txt
          pip install mlflow
      - name: Run MLProject
        run: mlflow run MLProject -P data_path=namadataset_preprocessing
